version: "3.7"

services:
  backend:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web


  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - backend
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  static-data:
