# Generated by Django 3.2 on 2021-11-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_city_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
