# Generated by Django 3.2 on 2021-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Name Surname'),
        ),
    ]
