# Generated by Django 3.2 on 2021-11-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_subjectfirst_subjectsecond'),
        ('university', '0004_auto_20211129_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_grant_point', to='university.specialty', verbose_name='Specialty')),
                ('subject_first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_first_grant', to='school.subjectfirst', verbose_name='First subject')),
                ('subject_second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_second_grant', to='school.subjectsecond', verbose_name='Second subject')),
            ],
        ),
    ]
