# Generated by Django 3.2 on 2021-12-17 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_stuff', to='university.university', verbose_name='University'),
        ),
    ]
