# Generated by Django 3.2 on 2021-12-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityPassPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_point', models.IntegerField(blank=True, null=True, verbose_name='Pass point for university')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_points', to='university.faculty', verbose_name='Faculty')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_points', to='university.specialty', verbose_name='Specialty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_points', to='university.university', verbose_name='University')),
            ],
        ),
    ]
