# Generated by Django 3.2 on 2021-12-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_userpasspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='estated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='faculties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='specialties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
